name: Build Docker image
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Build and push Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: c2d7fa/timespectre
          username: ${{secrets.docker_username}}
          password: ${{secrets.docker_password}}
          dockerfile: Dockerfile
          tags: latest
          snapshot: true
